import os

from pymongo import MongoClient
from pymongo.database import Database
from pymongo.collection import Collection

# Environment variables
MONGO_DB_URI = os.environ.get('MONGO_URI', 'mongodb://localhost:27017')
"""
Environmen variable of MongoDb connection URI string
    DEFAULT("'mongodb://localhost:27017')
"""

DATALAKE_DB_NAME = os.environ.get('DATALAKE_DB_NAME', 'datalake')
"""
Environment variable of database name.
    DEFAULT('datalake')
"""

DATALAKE_HOME_DIR = os.environ.get('DATALAKE_HOME_DIR', './raw')
"""
Relative directory path of data files.
    DEFAULT('./raw')
"""

SOURCE_DIRECTORY = os.path.abspath(DATALAKE_HOME_DIR) 
""" Autogenerated absolute path of source directory derived from 
    DATALAKE_HOME_DIR environment variable
"""

def loadDataFrom(srcFilePath, destCollName) :
"""
Loads data from source into destination where
    srcFilePath:    source absolute path of data file
    destCollName:   destination collection name
"""

     with open(srcFilePath, 'r') as  dataFile :
        line = dataFile.readline()  # Expect header fields on first line
        header = line.split(',')    # 

        for lines in dataFile.readlines(hint=100000) :
            for line in lines :
                colData = line.split(',')

                if len(header) == len(line) : #


    dataFile.close()


def man():
    loadRawDataFile()


if __name__ == "__main__":
    main()
